### ISSUE TITLE
오타 수정

### ISSUE THREAD

**Issue by gyeheon** [Sharlottes/KakaoBridge#1]
![image](https://user-images.githubusercontent.com/70797952/212102975-1f67a420-dcc7-4c18-9d00-4504a0a9a710.png)
"체팅" 오타가 있습니다

**Comment by Sharlottes** [comment]
https://github.com/Sharlottes/KakaoBridge/commit/851406ad53a1b88765c6191e2d671f32dc0c7cfb
+ 맞춤법 검사기로 추가 검사를 했습니다.
